name: reviewdog
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get latest release version
      id: style_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        excludes: prerelease, draft
        repository: mulesoft/dev-docs-writing-style
    - name: Download and extract
      uses: schmiddim/action-wget-unzip@v2
      with:
        url: https://github.com/mulesoft/dev-docs-writing-style/releases/download/${{steps.style_version.outputs.release}}/Mulesoft.zip
        destination: .github/Mulesoft
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.17.0
        fail_on_error: false
        reporter: github-pr-review
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
